# Generated by Django 4.0.3 on 2022-04-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
