# Generated by Django 4.0.3 on 2022-04-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_Reg', '0003_remove_registration_confirm_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
    ]
