# Generated by Django 4.0.3 on 2022-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_Reg', '0004_rename_registration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
