# Generated by Django 4.0.3 on 2022-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('model', models.CharField(max_length=45)),
                ('make', models.CharField(max_length=45)),
                ('year', models.DateField()),
                ('desc', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
