# Generated by Django 4.0.3 on 2022-04-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_exam_app', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='selles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='final_exam_app.user'),
        ),
    ]
