# Generated by Django 4.0.3 on 2022-04-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_exam_app', '0003_car_selles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='selles',
            new_name='seller',
        ),
    ]
